language: go

go:
  - "1.17"

services:
  - docker

before_install:
  # Install any dependencies or tools required for building your project
  - go mod download

after_success:
  # Build Docker image
  - docker build -t my-golang-app .

  # Run Docker container
  - docker run -d -p 3000:3000 --name my-app my-golang-app

  # Optional: Run additional tests against the running Docker container
  # - curl http://localhost:3000/healthcheck

# Configure notifications, if desired

# Additional configuration options as needed
