// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateUsers(ctx context.Context, arg CreateUsersParams) error
	FindUserByEmail(ctx context.Context, email string) (User, error)
	ResetPassword(ctx context.Context, arg ResetPasswordParams) error
}

var _ Querier = (*Queries)(nil)
