name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

      # Log in to Docker Hub or your registry provider
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # add your Docker Hub username to GitHub secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # add your Docker Hub password or token to GitHub secrets

    # Build Docker image
    - name: Build Docker image
      run: docker build -t xcurvnubaim/njajal-go:latest .
      
    # Push Docker image to registry
    - name: Push Docker image
      run: |
        docker push xcurvnubaim/njajal-go:latest
